# theme.toml template for a Hugo theme

name = "Formula1"
license = "MIT"
description = "Formula1-inspired theme for my webblog."
homepage = "https://protogia.github.io/formula1/"
tags = ["blog"]
features = ["blog"]
min_version = 0.1

[author]
  name = "Giancarlo Rizzo"
  homepage = "https://github.com/protogia"
