baseURL = 'https://protogia.github.io'
languageCode = 'en-us'
title = 'protogia.engineering'
theme = 'formula1'

[taxonomies]
  color = 'color'
  category = 'categories'
  tag = 'tags'

[Menu]
[[menu.Main]]
   identifier = "projects"
   name = "Projects"
   url = "/projects"

[[menu.Main]]
   identifier = "blog"
   name = "Evaluations"
   url = "/blog"