baseURL = 'https://protogia.github.io'
languageCode = 'en-us'
title = 'protogia.engineering'
theme = 'base16'

[taxonomies]
  category = 'categories'
  tag = 'tags'


[Menu]
   [[menu.Main]]
      identifier = "projects"
      name = " Projects"
      url = "/projects"
   [[menu.Main]]
      identifier = "blog"
      name = "Blog:offtopic"
      url = "/blog"
   [[menu.Main]]
      identifier = "jupyterlite"
      name = "Dataspace:jupyterlite"
      url = "https://protogia.github.io/jupyterlite"