baseURL = 'https://protogia.github.io'
languageCode = 'en-us'
title = 'protogia.engineering'
theme = 'base16'

[taxonomies]
  color = 'color'
  category = 'categories'
  tag = 'tags'

[Menu]
[[menu.Main]]
   identifier = "projects"
   name = "  Projects"
   url = "/projects"
[[menu.Main]]
   identifier = "blog"
   name = " Blog"
   url = "/blog"
[[menu.Main]]
   identifier = "gists"
   name = " Gists"
   url = "/gists"
[[menu.Main]]
   identifier = "favourites"
   name = "Favourites"
   url = "/favourites"
