baseURL = 'https://protogia.github.io'
languageCode = 'en-us'
title = 'protogia.engineering'
theme = 'base16'

[Menu]
 [[menu.Main]]
    identifier = "about"
    name = "About"
    url = "/about"
 [[menu.Main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
 [[menu.Main]]
    identifier = "offtopic"
    name = "Offtopic"
    url = "/offtopic"
