baseURL = 'https://protogia.github.io'
languageCode = 'en-us'
title = 'protogia.engineering'
theme = 'base16'

[taxonomies]
  category = 'categories'
  tag = 'tags'


[Menu]
[[menu.Main]]
   identifier = "projects"
   name = " Projekte"
   url = "/projects"
[[menu.Main]]
   identifier = "blog"
   name = "Blog:Offtopic"
   url = "/blog"